[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "robocop-custom-rules"
version = "0.1.0"
authors = [
    { name = "Kandrus", email = "kandrus@example.com" },
]
description = "Custom rules and checkers for Robocop linting."
readme = "" # No readme file needed for a simple plugin


[project.entry-points."robocop.plugins"]
robocop-custom-rules = "robocop_plugin.rules"



[tool.setuptools.packages]
find = { exclude = ["venv", "venv_robocop_plugin"] }

[tool.setuptools.package-data]
robocop_plugin = ["__init__.py"] # Ensure the package is recognized
